###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "rushil@hotmail.com",
    "firstName": "rushil",
    "lastName": "shakya",
    "password": "sek"
}
###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "email": "rushil@hotmail.com",
    "password": "sek"
}
###
POST http://localhost:3001/api/products/ HTTP/1.1
content-type: application/json

{
    "name": "pants",
    "price": 200,
    "stock": 100
}
###
GET http://localhost:3001/api/products/ HTTP/1.1
