###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "rushil@hotmail.com",
    "firstName": "rushil",
    "lastName": "shakya",
    "password": "sek"
}
###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "email": "rushil@hotmail.com",
    "password": "sek"
}
###
POST http://localhost:3001/api/products/ HTTP/1.1
content-type: application/json

{
    "name": "t-shirt",
    "price": 100,
    "stock": 100
}
###
GET http://localhost:3001/api/products/ HTTP/1.1
###
POST http://localhost:3001/api/cart/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1c2hpbEBob3RtYWlsLmNvbSIsImlkIjoxLCJmaXJzdE5hbWUiOiJydXNoaWwiLCJsYXN0TmFtZSI6InNoYWt5YSIsImlhdCI6MTY2Njk3Njg3NSwiZXhwIjoxNjY2OTgwNDc1fQ.67qTNg6Dus2RuG0scSc6o6h_iSN8Qyzbw4dihB6knFQ

{
    "product_id": 2,
    "quantity": 3
}
###
GET http://localhost:3001/api/cart/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1c2hpbEBob3RtYWlsLmNvbSIsImlkIjoxLCJmaXJzdE5hbWUiOiJydXNoaWwiLCJsYXN0TmFtZSI6InNoYWt5YSIsImlhdCI6MTY2Njk3Njg3NSwiZXhwIjoxNjY2OTgwNDc1fQ.67qTNg6Dus2RuG0scSc6o6h_iSN8Qyzbw4dihB6knFQ

