###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "email": "rushil@hotmail.com",
    "firstName": "rushil",
    "lastName": "shakya",
    "password": "sek"
}
###
POST http://localhost:3001/api/login/ HTTP/1.1
content-type: application/json

{
    "email": "rushila@hotmail.com",
    "password": "sek"
}
###
POST http://localhost:3001/api/products/ HTTP/1.1
content-type: application/json

{
    "name": "t-shirt",
    "price": 100,
    "stock": 100
}
###
GET http://localhost:3001/api/products/ HTTP/1.1
###
POST http://localhost:3001/api/cart/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1c2hpbGFAaG90bWFpbC5jb20iLCJpZCI6MiwiZmlyc3ROYW1lIjoicnVzaGlsIiwibGFzdE5hbWUiOiJzaGFreWEiLCJpYXQiOjE2NjcwMTIyMzIsImV4cCI6MTY2NzAxNTgzMn0.e-PuNJpVeOf36k2LkGTKLQt_kjflucAX8vWFGfRQcHA

{
    "product_id": 2,
    "quantity": 3
}
###
GET http://localhost:3001/api/cart/ HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1c2hpbGFAaG90bWFpbC5jb20iLCJpZCI6MiwiZmlyc3ROYW1lIjoicnVzaGlsIiwibGFzdE5hbWUiOiJzaGFreWEiLCJpYXQiOjE2NjcwMTIyMzIsImV4cCI6MTY2NzAxNTgzMn0.e-PuNJpVeOf36k2LkGTKLQt_kjflucAX8vWFGfRQcHA

